export const LOGIN_DEFAULT_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const HOMEANALYSE_ROUTE = '/home_analyse'
export const VISIT_ROUTE = '/visit'
export const CHAT_ROUTE = '/chat'