const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const visitRouter = require('./visitRouter')
const doctorRouter = require('./doctorRouter')
const hAnalyseRouter = require('./hAnalyseRouter')
router.use('/user', userRouter)
router.use('/visit', visitRouter)
router.use('/hAnalyse', hAnalyseRouter)
router.use('/doctor', doctorRouter)
module.exports = router